import type { Subscription } from "./types";

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "1",
    user_id: "mock",
    name: "Netflix",
    icon_url: null,
    category: "娱乐",
    type: "recurring",
    amount: 98,
    currency: "CNY",
    billing_cycle: "monthly",
    custom_cycle_days: null,
    next_billing: "2026-03-15",
    started_at: "2024-01-15",
    purchase_price: null,
    purchase_date: null,
    expected_lifespan_months: null,
    status: "active",
    notes: null,
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    user_id: "mock",
    name: "Spotify",
    icon_url: null,
    category: "娱乐",
    type: "recurring",
    amount: 15,
    currency: "CNY",
    billing_cycle: "monthly",
    custom_cycle_days: null,
    next_billing: "2026-03-08",
    started_at: "2023-06-01",
    purchase_price: null,
    purchase_date: null,
    expected_lifespan_months: null,
    status: "active",
    notes: null,
    created_at: "2023-06-01T00:00:00Z",
    updated_at: "2023-06-01T00:00:00Z",
  },
  {
    id: "3",
    user_id: "mock",
    name: "ChatGPT Plus",
    icon_url: null,
    category: "工具",
    type: "recurring",
    amount: 20,
    currency: "CNY",
    billing_cycle: "monthly",
    custom_cycle_days: null,
    next_billing: "2026-03-01",
    started_at: "2024-03-01",
    purchase_price: null,
    purchase_date: null,
    expected_lifespan_months: null,
    status: "active",
    notes: "GPT-4 access",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "4",
    user_id: "mock",
    name: "MacBook Pro 14",
    icon_url: null,
    category: "硬件",
    type: "lifetime",
    amount: null,
    currency: "CNY",
    billing_cycle: null,
    custom_cycle_days: null,
    next_billing: null,
    started_at: null,
    purchase_price: 17999,
    purchase_date: "2024-06-15",
    expected_lifespan_months: 48,
    status: "active",
    notes: "M3 Pro",
    created_at: "2024-06-15T00:00:00Z",
    updated_at: "2024-06-15T00:00:00Z",
  },
  {
    id: "5",
    user_id: "mock",
    name: "iCloud 200GB",
    icon_url: null,
    category: "云服务",
    type: "recurring",
    amount: 21,
    currency: "CNY",
    billing_cycle: "monthly",
    custom_cycle_days: null,
    next_billing: "2026-03-20",
    started_at: "2023-01-20",
    purchase_price: null,
    purchase_date: null,
    expected_lifespan_months: null,
    status: "active",
    notes: null,
    created_at: "2023-01-20T00:00:00Z",
    updated_at: "2023-01-20T00:00:00Z",
  },
  {
    id: "6",
    user_id: "mock",
    name: "Notion",
    icon_url: null,
    category: "工具",
    type: "recurring",
    amount: 96,
    currency: "CNY",
    billing_cycle: "yearly",
    custom_cycle_days: null,
    next_billing: "2026-09-01",
    started_at: "2024-09-01",
    purchase_price: null,
    purchase_date: null,
    expected_lifespan_months: null,
    status: "active",
    notes: "Personal Pro",
    created_at: "2024-09-01T00:00:00Z",
    updated_at: "2024-09-01T00:00:00Z",
  },
  {
    id: "7",
    user_id: "mock",
    name: "Figma",
    icon_url: null,
    category: "工具",
    type: "recurring",
    amount: 144,
    currency: "CNY",
    billing_cycle: "yearly",
    custom_cycle_days: null,
    next_billing: "2026-04-15",
    started_at: "2025-04-15",
    purchase_price: null,
    purchase_date: null,
    expected_lifespan_months: null,
    status: "active",
    notes: null,
    created_at: "2025-04-15T00:00:00Z",
    updated_at: "2025-04-15T00:00:00Z",
  },
  {
    id: "8",
    user_id: "mock",
    name: "Keep Premium",
    icon_url: null,
    category: "健康",
    type: "recurring",
    amount: 228,
    currency: "CNY",
    billing_cycle: "yearly",
    custom_cycle_days: null,
    next_billing: "2026-07-01",
    started_at: "2025-07-01",
    purchase_price: null,
    purchase_date: null,
    expected_lifespan_months: null,
    status: "active",
    notes: null,
    created_at: "2025-07-01T00:00:00Z",
    updated_at: "2025-07-01T00:00:00Z",
  },
  {
    id: "9",
    user_id: "mock",
    name: "AirPods Pro 2",
    icon_url: null,
    category: "硬件",
    type: "lifetime",
    amount: null,
    currency: "CNY",
    billing_cycle: null,
    custom_cycle_days: null,
    next_billing: null,
    started_at: null,
    purchase_price: 1899,
    purchase_date: "2025-01-10",
    expected_lifespan_months: 36,
    status: "active",
    notes: null,
    created_at: "2025-01-10T00:00:00Z",
    updated_at: "2025-01-10T00:00:00Z",
  },
  {
    id: "10",
    user_id: "mock",
    name: "Apple Developer",
    icon_url: null,
    category: "工具",
    type: "recurring",
    amount: 688,
    currency: "CNY",
    billing_cycle: "yearly",
    custom_cycle_days: null,
    next_billing: "2026-11-15",
    started_at: "2024-11-15",
    purchase_price: null,
    purchase_date: null,
    expected_lifespan_months: null,
    status: "active",
    notes: null,
    created_at: "2024-11-15T00:00:00Z",
    updated_at: "2024-11-15T00:00:00Z",
  },
];
